language: node_js
node_js:
    - "8"
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --disable-setuid-sandbox --no-sandbox --remote-debugging-port=9222 http://localhost &
script:
  - npm run test
notifications:
  email: false